### ISSUE TITLE
Project feedback

### ISSUE THREAD

**Issue by adamstep** [eutak/automatic-parakeet#1]
Hi @eutak , thanks for your submission! I was able to get it up and running well. The main improvements I noticed is better error messages and validation of the data. For example, I'm able to enter any string (or empty) for the phone number without any error. Ideally, you can use a library like https://django-phonenumber-field.readthedocs.io/ for the phone number field, which should automatically do validations as well. I also noticed the validation errors do not appear inline in the form, that would be a nice addition. Would you be able to make these updates?

Thanks,
Adam

**Comment by eutak** [comment]
Thanks @adamstep - will followup sometime in the next few days.

**Comment by eutak** [comment]
@adamstep Fixed here https://github.com/eutak/automatic-parakeet/pull/2

**Comment by adamstep** [comment]
Looks great now, thanks!
